mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    set_cookie_view,
    get_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    UserRegisterView,
    FooBarView,
    UsersListView,
    ProfileDetailView,
    ProfileUpdateView,
    UpdateAvatarView,
    HelloView,
)


app_name = "myauthapp"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"
    ),
    path("hello/", HelloView.as_view(), name="hello"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("about-me/update-avatar/<int:pk>/", UpdateAvatarView.as_view(), name="update_avatar"),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("users/<int:pk>/", ProfileDetailView.as_view(), name="profile_detail"),
    path("users/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile_update"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from .sitemaps import sitemaps


urlpatterns = [
    path('reqdata/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('blogapp/', include('blogapp.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    )
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls', namespace="myauth")),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
)


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/shopapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailView,
    ProductListView,
    OrdersListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    ProductsDataExportView,
    OrdersDataExportView,
    ProductViewSet,
    OrderViewSet,
    LatestProductFeed,
    UserOrdersListView,
    UserOrdersListExportView,
)


app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet, basename="products")
routers.register("orders", OrderViewSet, basename="orders")

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductListView.as_view(), name="products_list"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/latest/feed/", LatestProductFeed(), name="products-feed"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/export/", OrdersDataExportView.as_view(), name="orders-export"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("users/<int:user_id>/orders/", UserOrdersListView.as_view(), name="user_orders_list"),
    path("users/<int:user_id>/orders/export/", UserOrdersListExportView.as_view(), name="user_orders-export"),
]

mysite/shopapp/forms.py
from django import forms
from django.forms import ModelForm, ImageField, ClearableFileInput
from django.contrib.auth.models import Group

from .models import Product, Order


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ["name"]


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview"

    images = ImageField(
        widget=ClearableFileInput(attrs={"multiple": True})
    )


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = "user", "delivery_address", "promo_code", "products"


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

mysite/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные views интернет-магазина: по товарам, заказам и т.д.
"""

import logging
from csv import DictWriter
from timeit import default_timer

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Group, User
from django.contrib.syndication.views import Feed
from django.core.cache import cache
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse
from rest_framework.decorators import action
from rest_framework.filters import OrderingFilter, SearchFilter
from rest_framework.parsers import MultiPartParser
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from .common import save_csv_products, save_csv_orders
from .forms import ProductForm, OrderForm, GroupForm
from .models import Product, Order, ProductImage
from .serializers import ProductSerializer, OrderSerializer


logger = logging.getLogger(__name__)


@extend_schema(description="Product view CRUD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product.

    Полный CRUD для сущностей товара.
    """

    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = (
        DjangoFilterBackend,
        OrderingFilter,
        SearchFilter,
    )
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]
    search_fields = [
        "name",
        "description",
    ]

    @extend_schema(
        summary="Get one product by ID",
        description="Retrieves **product**, returns 404 if not found",
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description="Empty response, product by id not found"),
        }
    )
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):

        response = HttpResponse(content_type='text/csv')
        filename = "products-export.csv"
        response['Content-Disposition'] = f"attachment; filename={filename}"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            "description",
            "price",
            "discount",
            "created_by_id",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow(
                {field: getattr(product, field) for field in fields}
            )
        return response

    @action(methods=["post"], detail=False, parser_classes=[MultiPartParser,])
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES["file"].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)

    @method_decorator(cache_page(60))
    def list(self, request, *args, **kwargs):
        # print("Hello products list")
        return super().list(request, *args, **kwargs)


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = (
        DjangoFilterBackend,
        OrderingFilter,
        SearchFilter,
    )
    list_params = [
        "created_at",
        "delivery_address",
        "user"
    ]
    filterset_fields = list_params
    ordering_fields = list_params
    search_fields = list_params

    @action(methods=["post"], detail=False, parser_classes=[MultiPartParser, ])
    def upload_csv(self, request: Request):
        products = save_csv_orders(
            request.FILES["file"].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)


class ShopIndexView(View):

    # @method_decorator(cache_page(60))
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 999),
            ('Smartphone', 999),
        ]
        context = {
            "timer_running": default_timer(),
            "products": products,
            "items": 5,
        }
        logger.debug("Products for shop index %s", products)
        logger.info("Rendering shop index")
        print("Shop index context", context)
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)

        if form.is_valid():
            form.save()

        return redirect(request.path)


class ProductDetailView(DetailView):
    template_name = "shopapp/products-detail.html"
    # model = Product
    queryset = Product.objects.prefetch_related("images")
    context_object_name = "product"


class ProductListView(ListView):
    template_name = 'shopapp/products-list.html'
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)


class ProductCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        return self.request.user.is_superuser

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("shopapp:products_list")


class ProductUpdateView(UserPassesTestMixin, PermissionRequiredMixin, UpdateView):
    def test_func(self):
        return self.request.user.is_superuser or (
                self.permission_required and self.model.created_by
        )

    permission_required = "shopapp.change_product"
    model = Product
    form_class = ProductForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)

        for image in form.files.getlist("images"):
            ProductImage.objects.create(
                product=self.object,
                image=image
            )
        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects.
        select_related("user").
        prefetch_related('products')
    )


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order",
    queryset = (
        Order.objects.
        select_related("user").
        prefetch_related('products')
    )


class OrderCreateView(CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy("shopapp:orders_list")


class OrderUpdateView(UpdateView):
    model = Order
    form_class = OrderForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:order_details",
            kwargs={"pk": self.object.pk},
        )


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("shopapp:orders_list")


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        cache_key = "products_data_export"
        products_data = cache.get(cache_key)

        if products_data is None:
            products = Product.objects.order_by("pk").all()
            products_data = [
                {
                    "pk": product.pk,
                    "name": product.name,
                    "price": product.price,
                    "archived": product.archived,
                }
                for product in products
            ]
            cache.set(cache_key, products_data, 300)
            # elem = products_data[0]
            # name = elem["name"]
            # print("name", name)
        return JsonResponse({"products": products_data})


class OrdersDataExportView(UserPassesTestMixin, View):

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request: HttpRequest) -> JsonResponse:
        orders = Order.objects.order_by("pk").all()
        orders_data = [
            {
                "pk": order.pk,
                "delivery_address": order.delivery_address,
                "promo_code": order.promo_code,
                "user_id": order.user.pk,
                "products": [product.pk for product in order.products.all()],
            }
            for order in orders
        ]

        return JsonResponse({"orders": orders_data})


class LatestProductFeed(Feed):
    title = "Shop products (latest)"

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title%}
            Base title
        {% endblock %}
    </title>
</head>
<body>
    {% block body%}
        Base body
    {% endblock %}
    <br>
<div>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_weekday %}
    Today is {{ current_weekday }}
</div>
</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create order
{% endblock %}

{% block body %}
    <h1>Create a new order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Create
            </button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">
            Back to orders list
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">
                Create
            </button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Back to products list
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title%}
    Groups list
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        {% if not groups %}
            <h3>No group yet</h3>
        {% else %}
        <ul>
            {% for group in groups %}
            <li>
                <ul>
                <div>{{ group.name }}</div>
                {% for permission in group.permissions.all %}
                <li>
                    {{ permission.name }}
                    (<code>{{ permission.codename }}</code>)
                </li>
                {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete {{object.name }}
{% endblock %}

{% block body %}
    <h1>Do you really want to delete order #{{ object.pk }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order</a>
    </div>
<br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders: </h1>
    {% if object_list %}
        <div>
            {% for order in object_list %}
            <div>
                <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
                >Details #{{ order.pk }} </a></p>
                <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                <p>Promo-code: <code>{{ order.promo_code }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
                <div>Products in order:
                    <ul>
                        {% for product in order.products.all %}
                            <li>{{ product.name }} costs ${{ product.price }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}
    <div>
        <a href="{% url 'shopapp:order_create' %}">
            Create a new order
        </a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update order
{% endblock %}

{% block body %}
    <h1>Update order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
<br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=order.pk %}">Back to order #{{ object.pk }}</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archived {{object.name }}
{% endblock %}

{% block body %}
    <h1>Do you really want to archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">Back to product</a>
    </div>
<br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/products-detail.html
{% extends 'shopapp/base.html' %}
{% load i18n %}
{% block title %}
    {% translate 'Product' %} {{ product.pk }}
{% endblock %}

{% block body %}
    <h1>{% translate 'Product' %} <strong>{{ product.name }}</strong></h1>
    <div>
        <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
        <div>{% translate 'Price' %}: {{ product.price }}</div>
        <div>{% translate 'Discount' %}: {{ product.discount }}</div>
        <div>{% translate 'Archived' %}: {{ product.archived }}</div>
        <div>{% translate 'Created by' %}: {% firstof product.created_by.first_name product.created_by.username %}</div>

        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}

        <h3>{% translate 'Images' %}:</h3>
        {% if product.images.all %}
            <div>
            {% blocktranslate count images_count=product.images.all|length %}
                There is only one image.
                {% plural %}
                There are {{ images_count }} images.
            {% endblocktranslate %}
            </div>
            <div>
                {% for img in product.images.all %}
                    <div>
                        <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                        <div>
                            {{ img.description }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            {% url 'shopapp:product_update' pk=product.pk as upload_image_url%}
            {% blocktranslate %}
                <h3>No images uploaded yet</h3>
                <a href="{{ upload_image_url }}">
                Upload a new one</a>
            {% endblocktranslate %}
        {% endif %}
    </div>
<br>
    <div>
        <a href="{% url 'shopapp:product_update' pk=product.pk %}"
        >{% translate 'Update product'%}</a>
    </div>
<br>
    <div>
        <a href="{% url 'shopapp:product_delete' pk=product.pk%}"
        >{% translate 'Archive product' %}</a>
    </div>
<br>
    <div>
        <a href="{% url 'shopapp:products_list' %}"
        >{% translate 'Back to products list' %}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html'%}
{% load i18n %}
{% block title %}
    {% translate "Products list" %}
{% endblock %}

{% block body %}
    <h1>{{_("Products")}}:</h1>
    {% if products %}
        <div>
        {% blocktranslate count products_count=products|length %}
            There is only one product.
            {% plural %}
            There are {{ products_count }} products.
        {% endblocktranslate %}
        </div>
        <div>
            {% for product in products %}
                <div>
                    <p><a href="{% url 'shopapp:product_details' pk=product.pk %}"
                    >{% translate 'Name' context 'product name' %}: {{ product.name }}</a></p>
                    <p>{%  translate 'Price' %}: {{ product.price }}</p>
                    {% translate 'no discount' as no_discount %}
                    <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}%</p>

                    {% if product.preview %}
                        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                    {% endif %}
                    <br>
                </div>
            {% endfor %}
        </div>
        <div>
        <a href="{% url 'shopapp:product_create' %}">
            {% translate 'Create a new product' %}
        </a>
        </div>
    {% else %}
        {% url 'shopapp:product_create' as create_product_url%}
        {% blocktranslate %}
            <h3>No products yet</h3>
            <a href="{{ create_product_url }}">
            Create a new one</a>
        {% endblocktranslate %}
    {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
    {% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title%}
    Shop Index
{% endblock %}

{% block body%}
<h1>Hello Shop Index</h1>

<div>
    <ul>
        {% for name, price in products%}
            <li>{{ name }} for ${{ price }}</li>
            {% if name|length_is:'7'%}
            <span>Lucky index</span>
            {% endif %}
            {% if name|length_is:'6' %}
                <span>not Lucky product</span>
            {% endif %}
            {% if name|length_is:'10' %}
                <span>so long product</span>
            {% endif %}
        {% empty %}
            No products
        {% endfor %}
    </ul>
</div>
<div>
<strong>
    You have {{ items }} item{{ items|pluralize }}
</strong>
</div>
<div>
    Time running: {{ timer_running }}
</div>

{% cache 100 lorem products %}
<div>
    {% lorem 3 p random %}
</div>
{% endcache %}
{% endblock %}

mysite/shopapp/templates/shopapp/user_orders_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title%}
    Shop Index
{% endblock %}

{% block body%}
  {% if orders %}
    <h1>Пользователь {{ owner.username }} выполнил следующие заказы</h1>
      {% cache 60 user_orders owner.pk %}
      {% for order in orders %}
        <li>Order #{{ order.id }}: {{ order.delivery_address }} - {{ order.created_at }}</li>
      {% endfor %}
      {% endcache %}
  {% else %}
      <h1>У пользователя {{ owner.username }} ещё нет заказов</h1>
  {% endif %}
{% endblock %}