mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    set_cookie_view,
    get_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    UserRegisterView,
    FooBarView,
    UsersListView,
    ProfileDetailView,
    ProfileUpdateView,
    UpdateAvatarView,
    HelloView,
)


app_name = "myauthapp"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"
    ),
    path("hello/", HelloView.as_view(), name="hello"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("about-me/update-avatar/<int:pk>/", UpdateAvatarView.as_view(), name="update_avatar"),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("users/<int:pk>/", ProfileDetailView.as_view(), name="profile_detail"),
    path("users/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile_update"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from .sitemaps import sitemaps


urlpatterns = [
    path('reqdata/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('blogapp/', include('blogapp.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    )
]

urlpatterns += i18n_patterns(
    path('accounts/', include('myauth.urls', namespace="myauth")),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
)


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def profile_avatar_directory_path(instance: "Profile", filename: str) -> str:
    return "profile/profile_{pk}/avatar/{filename}".format(
        pk=instance.user.pk,
        filename=filename
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=profile_avatar_directory_path)

    def __str__(self) -> str:
        return f"Profile (pk={self.pk}, user={self.user!r})"

mysite/myauth/views.py
from random import random

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _, ngettext

from .models import Profile


class HelloView(View):
    welcome_text = _("welcome hello world")

    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get("items") or 0
        items = int(items_str)
        products_line = ngettext(
            "one product",
            "{count} products",
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_text}</h1>"
            f"<p><h2>{products_line}</h2></p>"
        )
    
    
class AboutMeView(DetailView):
    permission_required = "myauth.change_user"
    template_name = "myauth/about-me.html"
    model = Profile

    def get_object(self, queryset=None):
        return Profile.objects.get(user=self.request.user)


class UpdateAvatarView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        return self.request.user.is_superuser or (self.permission_required and self.model.user.pk)

    permission_required = "myauth.change_user"
    template_name = "myauth/update_avatar.html"
    model = Profile
    fields = "avatar",

    def get_success_url(self):
        return reverse(
            "myauth:about-me.html",
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)

        return response


class UserRegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class ProfileDetailView(DetailView):
    template_name = "myauth/profile_form.html"
    model = Profile
    context_object_name = "profile"


class ProfileUpdateView(UserPassesTestMixin, PermissionRequiredMixin, UpdateView):
    def test_func(self):
        return self.request.user.is_staff or (self.request.user.id == self.object.user_id)

    permission_required = "myauth.change_user"
    model = Profile
    fields = "bio", "avatar"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "myauth:profile_detail",
            kwargs={"pk": self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)

        return response


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")


class UsersListView(ListView):
    template_name = 'myauth/profiles-list.html'
    context_object_name = "users"
    queryset = User.objects.filter()


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


@cache_page(60)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r} + {random()}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")


class FooBarView(View):
    def get(self, response: HttpResponse) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load cache %}

{% block title %}
    About me
{% endblock %}

{% block body %}
    <h1>User info</h1>
    <div>
    Products available: {% now "u" %}
    </div>
    {% if user.is_authenticated %}
        {% cache 300 user_info user.username %}
        <h2>Details</h2>
        <p>
            {% if profile.avatar %}
                <img src="{{ profile.avatar.url }}" alt="{{ profile.avatar.name }}">
            {% else %}
                <div>No avatar uploaded yet</div>
            {% endif %}
        <div>
        <a href="{% url 'myauth:update_avatar' pk=user.pk %}">Update avatar</a>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>
        </div>
        <br>
        {% endcache %}
    <br>
    {% else %}
        <h2>User anonymous</h2>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/profile_form.html
{% extends 'myauth/base.html' %}

{% block title %}
    View profile
{% endblock %}

{% block body %}
    <h1>View profile</h1>
    {% if profile %}
    <div>
        <h2>Details</h2>
        <p>
            {% if profile.avatar %}
                <img src="{{ profile.avatar.url }}" alt="{{ profile.avatar.name }}">
            {% else %}
                <div>No avatar uploaded yet</div>
            {% endif %}
        </p>
        <p>Bio: {{ profile.bio }}</p>
    </div>
<br>
    <div>
        {% if perms.myauth.UserUpdateView %}
            <a href="{% url 'myauth:profile_update' pk=profile.pk %}">Update profile</a>
        {% endif %}
    </div>
<br>
    <div>
        <a href="{% url 'myauth:users_list' %}">Back to users list</a>
    </div>
    {% else %}
        <div>No profile created yet</div>
    {% endif %}

{% endblock %}

mysite/myauth/templates/myauth/profile_update_form.html
{% extends 'myauth/base.html' %}

{% block title %}
    Update profile
{% endblock %}

{% block body %}
    <h1>Update profile</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
<br>
    <div>
        <a href="{% url 'myauth:profile_detail' pk=user.profile.pk %}">Back to profile #{{ profile.pk }}</a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/profiles-list.html
{% extends 'myauth/base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <h1>Users: </h1>
    {% if users %}
        <div>
        {% for user in users %}
            {% if user.profile or request.user == object.user %}
            <div>
                <p><a href="{% url 'myauth:profile_detail' pk=user.profile.pk %}">
                    Name: {% firstof user.first_name user.username %}</a></p>
            </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Rgister">
    </form>

{% endblock %}

mysite/myauth/templates/myauth/update_avatar.html
{% extends 'myauth/base.html' %}

{% block title %}
    Update avatar
{% endblock %}

{% block body %}
    <h1>Update avatar</h1>
    {% if user.is_authenticated %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    <br>
    {% else %}
        <h2>User anonymous</h2>
    {% endif %}
{% endblock %}